version: '3.8'

services:
    web:
        build:
            context: ${PWD}
            dockerfile: docker/web/Dockerfile.production
        environment:
            FLASK_ENV: ${FLASK_ENV}
            FLASK_CONFIG: ${FLASK_CONFIG}
            GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
            PROJECT_ID: ${PROJECT_ID}
        volumes:
            - ${PWD}:/usr/src/app
        command: gunicorn --bind :8080 -w 4 -b 0.0.0.0:5000 wsgi:app
        ports:
            - "8080:8080"
            